var Zepto=function(){function g(b){return null==b?String(b):M[T.call(b)]||"object"}function h(b){return"function"==g(b)}function m(b){return null!=b&&b==b.window}function t(b){return null!=b&&b.nodeType==b.DOCUMENT_NODE}function B(b){return"object"==g(b)}function x(b){return B(b)&&!m(b)&&Object.getPrototypeOf(b)==Object.prototype}function y(b){return b instanceof Array}function A(b){return c.call(b,function(b){return null!=b})}function D(b){return b.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,
    "$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}function G(b){return b in N?N[b]:N[b]=new RegExp("(^|\\s)"+b+"(\\s|$)")}function C(b,a){return"number"!=typeof a||U[D(b)]?a:a+"px"}function F(b){return"children"in b?a.call(b.children):f.map(b.childNodes,function(b){if(1==b.nodeType)return b})}function E(b,a,I){for(k in a)I&&(x(a[k])||y(a[k]))?(x(a[k])&&!x(b[k])&&(b[k]={}),y(a[k])&&!y(b[k])&&(b[k]=[]),E(b[k],a[k],I)):a[k]!==n&&(b[k]=a[k])}function r(b,a){return null==a?
    f(b):f(b).filter(a)}function q(b,a,I,c){return h(a)?a.call(b,I,c):a}function u(b,a){var c=b.className,e=c&&c.baseVal!==n;if(a===n)return e?c.baseVal:c;e?c.baseVal=a:b.className=a}function w(b){var a;try{return b?"true"==b||("false"==b?!1:"null"==b?null:/^0|^\s/.test(b)||isNaN(a=Number(b))?/^[\[\{]/.test(b)?f.parseJSON(b):b:a):b}catch(c){return b}}function H(b,a){a(b);for(var c in b.childNodes)H(b.childNodes[c],a)}var n,k,f,z,d=[],a=d.slice,c=d.filter,e=window.document,v={},N={},U={"column-count":1,
        columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},l=/^\s*<(\w+|!)[^>]*>/,J=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,V=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,P=/^(?:body|html)$/i,W=/([A-Z])/g,X="val css html text data width height offset".split(" "),O=e.createElement("table"),Q=e.createElement("tr"),R={tr:e.createElement("tbody"),tbody:O,thead:O,tfoot:O,td:Q,th:Q,"*":e.createElement("div")},Y=/complete|loaded|interactive/,Z=/^[\w-]*$/,M={},T=M.toString,
    p={},K,L,S=e.createElement("div"),aa={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"};p.matches=function(b,a){if(!a||!b||1!==b.nodeType)return!1;var c=b.webkitMatchesSelector||b.mozMatchesSelector||b.oMatchesSelector||b.matchesSelector;if(c)return c.call(b,a);var e;e=b.parentNode;(c=!e)&&
(e=S).appendChild(b);e=~p.qsa(e,a).indexOf(b);c&&S.removeChild(b);return e};K=function(b){return b.replace(/-+(.)?/g,function(b,a){return a?a.toUpperCase():""})};L=function(b){return c.call(b,function(a,c){return b.indexOf(a)==c})};p.fragment=function(b,c,I){var d,g,v;J.test(b)&&(d=f(e.createElement(RegExp.$1)));d||(b.replace&&(b=b.replace(V,"<$1></$2>")),c===n&&(c=l.test(b)&&RegExp.$1),c in R||(c="*"),v=R[c],v.innerHTML=""+b,d=f.each(a.call(v.childNodes),function(){v.removeChild(this)}));x(I)&&(g=
    f(d),f.each(I,function(b,a){if(-1<X.indexOf(b))g[b](a);else g.attr(b,a)}));return d};p.Z=function(b,a){b=b||[];b.__proto__=f.fn;b.selector=a||"";return b};p.isZ=function(b){return b instanceof p.Z};p.init=function(b,a){var c;if(b)if("string"==typeof b)if(b=b.trim(),"<"==b[0]&&l.test(b))c=p.fragment(b,RegExp.$1,a),b=null;else{if(a!==n)return f(a).find(b);c=p.qsa(e,b)}else{if(h(b))return f(e).ready(b);if(p.isZ(b))return b;if(y(b))c=A(b);else if(B(b))c=[b],b=null;else if(l.test(b))c=p.fragment(b.trim(),
    RegExp.$1,a),b=null;else{if(a!==n)return f(a).find(b);c=p.qsa(e,b)}}else return p.Z();return p.Z(c,b)};f=function(b,a){return p.init(b,a)};f.extend=function(b){var c,e=a.call(arguments,1);"boolean"==typeof b&&(c=b,b=e.shift());e.forEach(function(a){E(b,a,c)});return b};p.qsa=function(b,c){var e,d="#"==c[0],g=!d&&"."==c[0],f=d||g?c.slice(1):c,v=Z.test(f);return t(b)&&v&&d?(e=b.getElementById(f))?[e]:[]:1!==b.nodeType&&9!==b.nodeType?[]:a.call(v&&!d?g?b.getElementsByClassName(f):b.getElementsByTagName(c):
    b.querySelectorAll(c))};f.contains=function(b,a){return b!==a&&b.contains(a)};f.type=g;f.isFunction=h;f.isWindow=m;f.isArray=y;f.isPlainObject=x;f.isEmptyObject=function(b){for(var a in b)return!1;return!0};f.inArray=function(b,a,c){return d.indexOf.call(a,b,c)};f.camelCase=K;f.trim=function(b){return null==b?"":String.prototype.trim.call(b)};f.uuid=0;f.support={};f.expr={};f.map=function(b,a){var c,e=[],d;if("number"==typeof b.length)for(d=0;d<b.length;d++)c=a(b[d],d),null!=c&&e.push(c);else for(d in b)c=
    a(b[d],d),null!=c&&e.push(c);return 0<e.length?f.fn.concat.apply([],e):e};f.each=function(b,a){var c;if("number"==typeof b.length)for(c=0;c<b.length&&!1!==a.call(b[c],c,b[c]);c++);else for(c in b)if(!1===a.call(b[c],c,b[c]))break;return b};f.grep=function(b,a){return c.call(b,a)};window.JSON&&(f.parseJSON=JSON.parse);f.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(b,a){M["[object "+a+"]"]=a.toLowerCase()});f.fn={forEach:d.forEach,reduce:d.reduce,push:d.push,
    sort:d.sort,indexOf:d.indexOf,concat:d.concat,map:function(b){return f(f.map(this,function(a,c){return b.call(a,c,a)}))},slice:function(){return f(a.apply(this,arguments))},ready:function(b){Y.test(e.readyState)&&e.body?b(f):e.addEventListener("DOMContentLoaded",function(){b(f)},!1);return this},get:function(b){return b===n?a.call(this):this[0<=b?b:b+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&
    this.parentNode.removeChild(this)})},each:function(b){d.every.call(this,function(a,c){return!1!==b.call(a,c,a)});return this},filter:function(b){return h(b)?this.not(this.not(b)):f(c.call(this,function(a){return p.matches(a,b)}))},add:function(b,a){return f(L(this.concat(f(b,a))))},is:function(b){return 0<this.length&&p.matches(this[0],b)},not:function(b){var c=[];if(h(b)&&b.call!==n)this.each(function(a){b.call(this,a)||c.push(this)});else{var e="string"==typeof b?this.filter(b):"number"==typeof b.length&&
    h(b.item)?a.call(b):f(b);this.forEach(function(b){0>e.indexOf(b)&&c.push(b)})}return f(c)},has:function(b){return this.filter(function(){return B(b)?f.contains(this,b):f(this).find(b).size()})},eq:function(b){return-1===b?this.slice(b):this.slice(b,+b+1)},first:function(){var b=this[0];return b&&!B(b)?b:f(b)},last:function(){var b=this[this.length-1];return b&&!B(b)?b:f(b)},find:function(b){var a=this;return"object"==typeof b?f(b).filter(function(){var b=this;return d.some.call(a,function(a){return f.contains(a,
        b)})}):1==this.length?f(p.qsa(this[0],b)):this.map(function(){return p.qsa(this,b)})},closest:function(b,a){var c=this[0],e=!1;for("object"==typeof b&&(e=f(b));c&&!(e?0<=e.indexOf(c):p.matches(c,b));)c=c!==a&&!t(c)&&c.parentNode;return f(c)},parents:function(b){for(var a=[],c=this;0<c.length;)c=f.map(c,function(b){if((b=b.parentNode)&&!t(b)&&0>a.indexOf(b))return a.push(b),b});return r(a,b)},parent:function(b){return r(L(this.pluck("parentNode")),b)},children:function(b){return r(this.map(function(){return F(this)}),
        b)},contents:function(){return this.map(function(){return a.call(this.childNodes)})},siblings:function(b){return r(this.map(function(b,a){return c.call(F(a.parentNode),function(b){return b!==a})}),b)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(b){return f.map(this,function(a){return a[b]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==getComputedStyle(this,"").getPropertyValue("display")){var b=this.style,
        a=this.nodeName,c,d;v[a]||(c=e.createElement(a),e.body.appendChild(c),d=getComputedStyle(c,"").getPropertyValue("display"),c.parentNode.removeChild(c),"none"==d&&(d="block"),v[a]=d);b.display=v[a]}})},replaceWith:function(b){return this.before(b).remove()},wrap:function(b){var a=h(b);if(this[0]&&!a)var c=f(b).get(0),e=c.parentNode||1<this.length;return this.each(function(d){f(this).wrapAll(a?b.call(this,d):e?c.cloneNode(!0):c)})},wrapAll:function(b){if(this[0]){f(this[0]).before(b=f(b));for(var a;(a=
        b.children()).length;)b=a.first();f(b).append(this)}return this},wrapInner:function(b){var a=h(b);return this.each(function(c){var e=f(this),d=e.contents();c=a?b.call(this,c):b;d.length?d.wrapAll(c):e.append(c)})},unwrap:function(){this.parent().each(function(){f(this).replaceWith(f(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(b){return this.each(function(){var a=f(this);
        (b===n?"none"==a.css("display"):b)?a.show():a.hide()})},prev:function(b){return f(this.pluck("previousElementSibling")).filter(b||"*")},next:function(b){return f(this.pluck("nextElementSibling")).filter(b||"*")},html:function(b){return 0===arguments.length?0<this.length?this[0].innerHTML:null:this.each(function(a){var c=this.innerHTML;f(this).empty().append(q(this,b,a,c))})},text:function(b){return 0===arguments.length?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=b===
    n?"":""+b})},attr:function(b,a){var c;return"string"==typeof b&&a===n?0==this.length||1!==this[0].nodeType?n:"value"==b&&"INPUT"==this[0].nodeName?this.val():!(c=this[0].getAttribute(b))&&b in this[0]?this[0][b]:c:this.each(function(c){if(1===this.nodeType)if(B(b))for(k in b){c=k;var e=b[k];null==e?this.removeAttribute(c):this.setAttribute(c,e)}else c=q(this,a,c,this.getAttribute(b)),null==c?this.removeAttribute(b):this.setAttribute(b,c)})},removeAttr:function(b){return this.each(function(){1===this.nodeType&&
    this.removeAttribute(b)})},prop:function(b,a){b=aa[b]||b;return a===n?this[0]&&this[0][b]:this.each(function(c){this[b]=q(this,a,c,this[b])})},data:function(b,a){var c=this.attr("data-"+b.replace(W,"-$1").toLowerCase(),a);return null!==c?w(c):n},val:function(b){return 0===arguments.length?this[0]&&(this[0].multiple?f(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value):this.each(function(a){this.value=q(this,b,a,this.value)})},offset:function(b){if(b)return this.each(function(a){var c=
        f(this);a=q(this,b,a,c.offset());var e=c.offsetParent().offset();a={top:a.top-e.top,left:a.left-e.left};"static"==c.css("position")&&(a.position="relative");c.css(a)});if(0==this.length)return null;var a=this[0].getBoundingClientRect();return{left:a.left+window.pageXOffset,top:a.top+window.pageYOffset,width:Math.round(a.width),height:Math.round(a.height)}},css:function(b,a){if(2>arguments.length){var c=this[0],e=getComputedStyle(c,"");if(!c)return;if("string"==typeof b)return c.style[K(b)]||e.getPropertyValue(b);
        if(y(b)){var d={};f.each(y(b)?b:[b],function(b,a){d[a]=c.style[K(a)]||e.getPropertyValue(a)});return d}}var v="";if("string"==g(b))a||0===a?v=D(b)+":"+C(b,a):this.each(function(){this.style.removeProperty(D(b))});else for(k in b)b[k]||0===b[k]?v+=D(k)+":"+C(k,b[k])+";":this.each(function(){this.style.removeProperty(D(k))});return this.each(function(){this.style.cssText+=";"+v})},index:function(b){return b?this.indexOf(f(b)[0]):this.parent().children().indexOf(this[0])},hasClass:function(b){return b?
        d.some.call(this,function(b){return this.test(u(b))},G(b)):!1},addClass:function(b){return b?this.each(function(a){z=[];var c=u(this);q(this,b,a,c).split(/\s+/g).forEach(function(b){f(this).hasClass(b)||z.push(b)},this);z.length&&u(this,c+(c?" ":"")+z.join(" "))}):this},removeClass:function(b){return this.each(function(a){if(b===n)return u(this,"");z=u(this);q(this,b,a,z).split(/\s+/g).forEach(function(b){z=z.replace(G(b)," ")});u(this,z.trim())})},toggleClass:function(b,a){return b?this.each(function(c){var e=
        f(this);q(this,b,c,u(this)).split(/\s+/g).forEach(function(b){(a===n?!e.hasClass(b):a)?e.addClass(b):e.removeClass(b)})}):this},scrollTop:function(b){if(this.length){var a="scrollTop"in this[0];return b===n?a?this[0].scrollTop:this[0].pageYOffset:this.each(a?function(){this.scrollTop=b}:function(){this.scrollTo(this.scrollX,b)})}},scrollLeft:function(b){if(this.length){var a="scrollLeft"in this[0];return b===n?a?this[0].scrollLeft:this[0].pageXOffset:this.each(a?function(){this.scrollLeft=b}:function(){this.scrollTo(b,
        this.scrollY)})}},position:function(){if(this.length){var b=this[0],a=this.offsetParent(),c=this.offset(),e=P.test(a[0].nodeName)?{top:0,left:0}:a.offset();c.top-=parseFloat(f(b).css("margin-top"))||0;c.left-=parseFloat(f(b).css("margin-left"))||0;e.top+=parseFloat(f(a[0]).css("border-top-width"))||0;e.left+=parseFloat(f(a[0]).css("border-left-width"))||0;return{top:c.top-e.top,left:c.left-e.left}}},offsetParent:function(){return this.map(function(){for(var b=this.offsetParent||e.body;b&&!P.test(b.nodeName)&&
    "static"==f(b).css("position");)b=b.offsetParent;return b})}};f.fn.detach=f.fn.remove;["width","height"].forEach(function(b){var a=b.replace(/./,function(b){return b[0].toUpperCase()});f.fn[b]=function(c){var e,d=this[0];return c===n?m(d)?d["inner"+a]:t(d)?d.documentElement["scroll"+a]:(e=this.offset())&&e[b]:this.each(function(a){d=f(this);d.css(b,q(this,c,a,d[b]()))})}});["after","prepend","before","append"].forEach(function(b,a){var c=a%2;f.fn[b]=function(){var b,e=f.map(arguments,function(a){b=
    g(a);return"object"==b||"array"==b||null==a?a:p.fragment(a)}),d,v=1<this.length;return 1>e.length?this:this.each(function(b,g){d=c?g:g.parentNode;g=0==a?g.nextSibling:1==a?g.firstChild:2==a?g:null;e.forEach(function(b){if(v)b=b.cloneNode(!0);else if(!d)return f(b).remove();H(d.insertBefore(b,g),function(b){null==b.nodeName||"SCRIPT"!==b.nodeName.toUpperCase()||b.type&&"text/javascript"!==b.type||b.src||window.eval.call(window,b.innerHTML)})})})};f.fn[c?b+"To":"insert"+(a?"Before":"After")]=function(a){f(a)[b](this);
    return this}});p.Z.prototype=f.fn;p.uniq=L;p.deserializeValue=w;f.zepto=p;return f}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(g){function h(a){return a._zid||(a._zid=G++)}function m(a,c,e,d){c=t(c);if(c.ns)var g=new RegExp("(?:^| )"+c.ns.replace(" "," .* ?")+"(?: |$)");return(q[h(a)]||[]).filter(function(a){return a&&(!c.e||a.e==c.e)&&(!c.ns||g.test(a.ns))&&(!e||h(a.fn)===h(e))&&(!d||a.sel==d)})}function t(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function B(a){return n[a]||w&&H[a]||a}function x(a,c,e,d,f,m,l){var J=h(a),k=q[J]||(q[J]=[]);c.split(/\s/).forEach(function(c){if("ready"==
    c)return g(document).ready(e);var h=t(c);h.fn=e;h.sel=f;h.e in n&&(e=function(a){var c=a.relatedTarget;if(!c||c!==this&&!g.contains(this,c))return h.fn.apply(this,arguments)});var J=(h.del=m)||e;h.proxy=function(c){c=A(c);if(!c.isImmediatePropagationStopped()){c.data=d;var e=J.apply(a,c._args==C?[c]:[c].concat(c._args));!1===e&&(c.preventDefault(),c.stopPropagation());return e}};h.i=k.length;k.push(h);"addEventListener"in a&&a.addEventListener(B(h.e),h.proxy,h.del&&!w&&h.e in H||!!l)})}function y(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c,e,d,g){var f=h(a);(c||"").split(/\s/).forEach(function(c){m(a,c,e,d).forEach(function(c){delete q[f][c.i];"removeEventListener"in a&&a.removeEventListener(B(c.e),c.proxy,c.del&&!w&&c.e in H||!!g)})})}function A(a,c){if(c||!a.isDefaultPrevented)if(c||(c=a),g.each(d,function(e,d){var g=c[e];a[e]=function(){this[d]=k;return g&&g.apply(c,arguments)};a[d]=f}),c.defaultPrevented!==C?c.defaultPrevented:"returnValue"in c?!1===c.returnValue:c.getPreventDefault&&c.getPreventDefault())a.isDefaultPrevented=
    k;return a}function D(a){var c,e={originalEvent:a};for(c in a)z.test(c)||a[c]===C||(e[c]=a[c]);return A(e,a)}var G=1,C,F=Array.prototype.slice,E=g.isFunction,r=function(a){return"string"==typeof a},q={},u={},w="onfocusin"in window,H={focus:"focusin",blur:"focusout"},n={mouseenter:"mouseover",mouseleave:"mouseout"};u.click=u.mousedown=u.mouseup=u.mousemove="MouseEvents";g.event={add:x,remove:y};g.proxy=function(a,c){if(E(a)){var e=function(){return a.apply(c,arguments)};e._zid=h(a);return e}if(r(c))return g.proxy(a[c],
    a);throw new TypeError("expected function");};g.fn.bind=function(a,c,e){return this.on(a,c,e)};g.fn.unbind=function(a,c){return this.off(a,c)};g.fn.one=function(a,c,e,d){return this.on(a,c,e,d,1)};var k=function(){return!0},f=function(){return!1},z=/^([A-Z]|returnValue$|layer[XY]$)/,d={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};g.fn.delegate=function(a,c,e){return this.on(c,a,e)};g.fn.undelegate=function(a,c,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      e){return this.off(c,a,e)};g.fn.live=function(a,c){g(document.body).delegate(this.selector,a,c);return this};g.fn.die=function(a,c){g(document.body).undelegate(this.selector,a,c);return this};g.fn.on=function(a,c,e,d,h){var m,l,k=this;if(a&&!r(a))return g.each(a,function(a,d){k.on(a,c,e,d,h)}),k;r(c)||E(d)||!1===d||(d=e,e=c,c=C);if(E(e)||!1===e)d=e,e=C;!1===d&&(d=f);return k.each(function(f,k){h&&(m=function(a){y(k,a.type,d);return d.apply(this,arguments)});c&&(l=function(a){var e,f=g(a.target).closest(c,
    k).get(0);if(f&&f!==k)return e=g.extend(D(a),{currentTarget:f,liveFired:k}),(m||d).apply(f,[e].concat(F.call(arguments,1)))});x(k,a,d,e,c,l||m)})};g.fn.off=function(a,c,e){var d=this;if(a&&!r(a))return g.each(a,function(a,e){d.off(a,c,e)}),d;r(c)||E(e)||!1===e||(e=c,c=C);!1===e&&(e=f);return d.each(function(){y(this,a,e,c)})};g.fn.trigger=function(a,c){a=r(a)||g.isPlainObject(a)?g.Event(a):A(a);a._args=c;return this.each(function(){"dispatchEvent"in this?this.dispatchEvent(a):g(this).triggerHandler(a,
    c)})};g.fn.triggerHandler=function(a,c){var e,d;this.each(function(f,h){e=D(r(a)?g.Event(a):a);e._args=c;e.target=h;g.each(m(h,a.type||a),function(a,c){d=c.proxy(e);if(e.isImmediatePropagationStopped())return!1})});return d};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(a){g.fn[a]=function(c){return c?this.bind(a,c):this.trigger(a)}});["focus","blur"].forEach(function(a){g.fn[a]=
    function(c){c?this.bind(a,c):this.each(function(){try{this[a]()}catch(c){}});return this}});g.Event=function(a,c){r(a)||(c=a,a=c.type);var d=document.createEvent(u[a]||"Events"),g=!0;if(c)for(var f in c)"bubbles"==f?g=!!c[f]:d[f]=c[f];d.initEvent(a,g,!0);return A(d)}})(Zepto);
(function(g){function h(d,a,c,e){if(d.global)return d=a||q,c=g.Event(c),g(d).trigger(c,e),!c.isDefaultPrevented()}function m(d){d.global&&0===g.active++&&h(d,null,"ajaxStart")}function t(d,a){var c=a.context;if(!1===a.beforeSend.call(c,d,a)||!1===h(a,c,"ajaxBeforeSend",[d,a]))return!1;h(a,c,"ajaxSend",[d,a])}function B(d,a,c,e){var g=c.context;c.success.call(g,d,"success",a);e&&e.resolveWith(g,[d,"success",a]);h(c,g,"ajaxSuccess",[a,c,d]);y("success",a,c)}function x(d,a,c,e,g){var f=e.context;e.error.call(f,
    c,a,d);g&&g.rejectWith(f,[c,a,d]);h(e,f,"ajaxError",[c,e,d||a]);y(a,c,e)}function y(d,a,c){var e=c.context;c.complete.call(e,a,d);h(c,e,"ajaxComplete",[a,c]);c.global&&!--g.active&&h(c,null,"ajaxStop")}function A(){}function D(d){d&&(d=d.split(";",2)[0]);return d&&("text/html"==d?"html":"application/json"==d?"json":n.test(d)?"script":k.test(d)&&"xml")||"text"}function G(d,a){return""==a?d:(d+"&"+a).replace(/[&?]{1,2}/,"?")}function C(d){d.processData&&d.data&&"string"!=g.type(d.data)&&(d.data=g.param(d.data,
    d.traditional));!d.data||d.type&&"GET"!=d.type.toUpperCase()||(d.url=G(d.url,d.data),d.data=void 0)}function F(d,a,c,e){var f=!g.isFunction(a);return{url:d,data:f?a:void 0,success:f?g.isFunction(c)?c:void 0:a,dataType:f?e||c:c}}function E(d,a,c,e){var f,h=g.isArray(a),k=g.isPlainObject(a);g.each(a,function(a,m){f=g.type(m);e&&(a=c?e:e+"["+(k||"object"==f||"array"==f?a:"")+"]");!e&&h?d.add(m.name,m.value):"array"==f||!c&&"object"==f?E(d,m,c,a):d.add(a,m)})}var r=0,q=window.document,u,w,H=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
    n=/^(?:text|application)\/javascript/i,k=/^(?:text|application)\/xml/i,f=/^\s*$/;g.active=0;g.ajaxJSONP=function(d,a){if(!("type"in d))return g.ajax(d);var c=d.jsonpCallback,e=(g.isFunction(c)?c():c)||"jsonp"+(r+=1),f=q.createElement("script"),h=window[e],m,l=function(a){g(f).triggerHandler("error",a||"abort")},k={abort:l},n;a&&a.promise(k);g(f).on("load error",function(c,l){clearTimeout(n);g(f).off().remove();"error"!=c.type&&m?B(m[0],k,d,a):x(null,l||"error",k,d,a);window[e]=h;m&&g.isFunction(h)&&
h(m[0]);h=m=void 0});if(!1===t(k,d))return l("abort"),k;window[e]=function(){m=arguments};f.src=d.url.replace(/=\?/,"="+e);q.head.appendChild(f);0<d.timeout&&(n=setTimeout(function(){l("timeout")},d.timeout));return k};g.ajaxSettings={type:"GET",beforeSend:A,success:A,error:A,complete:A,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:"application/json",xml:"application/xml, text/xml",html:"text/html",
    text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};g.ajax=function(d){var a=g.extend({},d||{}),c=g.Deferred&&g.Deferred();for(u in g.ajaxSettings)void 0===a[u]&&(a[u]=g.ajaxSettings[u]);m(a);a.crossDomain||(a.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(a.url)&&RegExp.$2!=window.location.host);a.url||(a.url=window.location.toString());C(a);!1===a.cache&&(a.url=G(a.url,"_="+Date.now()));var e=a.dataType;d=/=\?/.test(a.url);if("jsonp"==e||d)return d||(a.url=G(a.url,a.jsonp?a.jsonp+"=?":
    !1===a.jsonp?"":"callback=?")),g.ajaxJSONP(a,c);d=a.accepts[e];var h={},k=function(a,c){h[a.toLowerCase()]=[a,c]},n=/^([\w-]+:)\/\//.test(a.url)?RegExp.$1:window.location.protocol,l=a.xhr(),q=l.setRequestHeader,r;c&&c.promise(l);a.crossDomain||k("X-Requested-With","XMLHttpRequest");k("Accept",d||"*/*");if(d=a.mimeType||d)-1<d.indexOf(",")&&(d=d.split(",",2)[0]),l.overrideMimeType&&l.overrideMimeType(d);(a.contentType||!1!==a.contentType&&a.data&&"GET"!=a.type.toUpperCase())&&k("Content-Type",a.contentType||
    "application/x-www-form-urlencoded");if(a.headers)for(w in a.headers)k(w,a.headers[w]);l.setRequestHeader=k;l.onreadystatechange=function(){if(4==l.readyState){l.onreadystatechange=A;clearTimeout(r);var d,h=!1;if(200<=l.status&&300>l.status||304==l.status||0==l.status&&"file:"==n){e=e||D(a.mimeType||l.getResponseHeader("content-type"));d=l.responseText;try{"script"==e?(0,eval)(d):"xml"==e?d=l.responseXML:"json"==e&&(d=f.test(d)?null:g.parseJSON(d))}catch(k){h=k}h?x(h,"parsererror",l,a,c):B(d,l,a,
    c)}else x(l.statusText||null,l.status?"error":"abort",l,a,c)}};if(!1===t(l,a))return l.abort(),x(null,"abort",l,a,c),l;if(a.xhrFields)for(w in a.xhrFields)l[w]=a.xhrFields[w];l.open(a.type,a.url,"async"in a?a.async:!0,a.username,a.password);for(w in h)q.apply(l,h[w]);0<a.timeout&&(r=setTimeout(function(){l.onreadystatechange=A;l.abort();x(null,"timeout",l,a,c)},a.timeout));l.send(a.data?a.data:null);return l};g.get=function(d,a,c,e){return g.ajax(F.apply(null,arguments))};g.post=function(d,a,c,e){var f=
    F.apply(null,arguments);f.type="POST";return g.ajax(f)};g.getJSON=function(d,a,c){var e=F.apply(null,arguments);e.dataType="json";return g.ajax(e)};g.fn.load=function(d,a,c){if(!this.length)return this;var e=this,f=d.split(/\s/),h;d=F(d,a,c);var k=d.success;1<f.length&&(d.url=f[0],h=f[1]);d.success=function(a){e.html(h?g("<div>").html(a.replace(H,"")).find(h):a);k&&k.apply(e,arguments)};g.ajax(d);return this};var z=encodeURIComponent;g.param=function(d,a){var c=[];c.add=function(a,c){this.push(z(a)+
    "="+z(c))};E(c,d,a);return c.join("&").replace(/%20/g,"+")}})(Zepto);
(function(g){g.fn.serializeArray=function(){var h=[],m;g([].slice.call(this.get(0).elements)).each(function(){m=g(this);var t=m.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&!this.disabled&&"submit"!=t&&"reset"!=t&&"button"!=t&&("radio"!=t&&"checkbox"!=t||this.checked)&&h.push({name:m.attr("name"),value:m.val()})});return h};g.fn.serialize=function(){var g=[];this.serializeArray().forEach(function(m){g.push(encodeURIComponent(m.name)+"="+encodeURIComponent(m.value))});return g.join("&")};
    g.fn.submit=function(h){h?this.bind("submit",h):this.length&&(h=g.Event("submit"),this.eq(0).trigger(h),h.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);(function(g){"__proto__"in{}||g.extend(g.zepto,{Z:function(h,t){h=h||[];g.extend(h,g.fn);h.selector=t||"";h.__Z=!0;return h},isZ:function(h){return"array"===g.type(h)&&"__Z"in h}});try{getComputedStyle(void 0)}catch(m){var h=getComputedStyle;window.getComputedStyle=function(g){try{return h(g)}catch(m){return null}}}})(Zepto);
Zepto.getScript=function(g,h){var m=document.createElement("script");m.async="async";m.src=g;m.onload=h||function(){};document.getElementsByTagName("head")[0].appendChild(m)};
